### ISSUE TITLE
parallel execution

### ISSUE THREAD

**Issue by asheetal** [thepira/cv.glmmLasso#25]
Is there a way to parallelize the lambda search? 

for example, if `nlambdas = 100` and I have 64 core CPU, would be great to shorten the search time.

**Comment by jaredlander** [comment]
Theoretically, the fit can be computed for each lambda independently, implying it can be done in parallel. The thing is, each subsequent fit starts with the results of the previous fit in order to speed up the fitting process.

So the question becomes, what creates more speed, providing the prior fit as a starting point for a subsequent fit or running in parallel? I'm not sure what the answer is.

**Comment by asheetal** [comment]
Thanks @jaredlander 
I did just that.
I created lambdas vector and used mclapply over that vector. ie, single cv fit each value of lambda

Now I am having a problem of model selection. Which is my best model? what is the best model selection criteria internally in cv.glmmLasso?

**Comment by jaredlander** [comment]
It's some measure of error depending on the type of outcome variable. That is supplied by glmmLasso and should be something like RMSE, logloss, AUC and the like.

**Comment by asheetal** [comment]
Ah. yes 
Thank you
